name: Fly Deploy
on:
push:
branches:
  - jgenso-issue-2-github-action
env:
FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
deploy:
name: Deploy Dems Llama
runs-on: ubuntu-latest
steps:
  - uses: actions/checkout@v3
  - uses: superfly/flyctl-actions/setup-flyctl@master
  - run: flyctl deploy --remote-only
